ktor {
  deployment {
    port = 8080
  }

  application {
    modules = [ com.example.ApplicationKt.module ]
  }
}

geo {
  database {
    # Use environment variable if set, otherwise use classpath resource
    path = ${?GEO_DATABASE_PATH}"classpath:GeoLite2-Country.mmdb"}
}